/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author rubco
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
        
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        
        g2d.setColor(new Color(112, 19, 37));
        g2d.fillRect(0, 0, 1500, 1000);
        
        g2d.setColor(new Color(68, 4, 26));
        int[] xPunto = new int[]{50,0, 1450, 1500};
        int[] yPunto = new int[]{1000, 950, 0, 50};
        g2d.fillPolygon(xPunto, yPunto, 4);
        g2d.fillRect(1450, 0, 50, 50);
        g2d.fillRect(0, 950, 50, 50);
        
        g2d.setColor(Color.BLACK);
        
        xPunto = new int[]{
            0,
            150,
            1500,
            1350
        };
        
        yPunto = new int[]{
            150,
            0,
            850,
            1000
        };
        
        g2d.fillPolygon(xPunto, yPunto, 4);
        g2d.fillRect(0, 0, 150, 150);
        g2d.fillRect(1350, 850, 150, 150);
        
        g2d.setColor(new Color(147, 15, 53));
        
        xPunto = new int[]{0,150, 1500, 1500};
        yPunto = new int[]{0, 0, 850, 945};
        g2d.fillPolygon(xPunto, yPunto, 4);
        
        g2d.setColor(new Color(127, 67, 34));
        xPunto = new int[]{580,780, 930, 725};
        yPunto = new int[]{530, 390, 485, 620};
        g2d.fillPolygon(xPunto, yPunto, 4);
        
        
    } 
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
