/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Derecha;
import Modelo.Izquierda;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;

/**
 *
 * @author rubco
 */
public class PasarelaPanel extends javax.swing.JPanel {

    private Image izqIma;
    private Image derIma;
    
    /**
     * Creates new form PasarelaPanel
     */
    public PasarelaPanel() {
        initComponents();
        izqIma = new ImageIcon(getClass().getResource("/Imagenes/IzquierdoChild.png")).getImage(); 
        derIma = new ImageIcon(getClass().getResource("/Imagenes/DerechoChild.png")).getImage(); 
    }
    
    
     @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        g2d.setColor(Color.WHITE);
        g2d.setFont(new Font("Segoe UI", Font.BOLD, 18));
        int i = 0;
        for(Izquierda izq : Main.Generador.pasarela.getPasarelaIzq()){
            g2d.drawImage(izqIma,600 + (70 * i), 450 - (50 * i), 80, 95, this);
            g2d.drawString("" +izq.getIdent(), 600 + (70 * i), 460 - (50 * i));
            i++;
        }
        
        i = 0;
        for(Derecha der: Main.Generador.pasarela.getPasarelaDer()){
            g2d.drawImage(derIma,830 - (70*i), 400 + (50*i), 80, 95, this);
            g2d.drawString("" + der.getIdent(), 830 -(70*i), 410 + (50*i));
            i++;
        }
        
        i=0;
        for(Izquierda izq : Main.Generador.pasarela.getColaIzquierda()){
            g2d.drawImage(izqIma,870 + (70 * i), 315 - (50 * i), 80, 95, this);
            g2d.drawString("" + izq.getIdent(), 870 + (70*i), 305 - (50*i));
            i++;
        }
        
        i=0;
        for(Derecha der : Main.Generador.pasarela.getColaDerecha()){
            g2d.drawImage(derIma,530 - (70*i), 540 + (50*i), 80, 95, this);
            g2d.drawString("" + der.getIdent(), 530 - (70*i), 550 + (50*i)); 
            i++;
        }
        
        
        
    }
    
    //Proporcion Izq 1,187
    //Proporcion Der 1,196
    
    //Puente izquierdo
    /*
        g2d.drawImage(izqIma,600, 450, 80, 95, this);
        g2d.drawImage(izqIma,670, 400, 80, 95, this);
        g2d.drawImage(izqIma,740, 350, 80, 95, this);
    */
    
    //Cola izquierda
    /*
        g2d.drawImage(izqIma,840, 335, 80, 95, this);
        g2d.drawImage(izqIma,910, 285, 80, 95, this);
        g2d.drawImage(izqIma,980, 235, 80, 95, this);
    */
    
    //Puente derecho
    /*
        g2d.drawImage(derIma,690, 500, 80, 95, this);
        g2d.drawImage(derIma,760, 450, 80, 95, this);
        g2d.drawImage(derIma,830, 400, 80, 95, this);
    */
    
    //Cola derecha
    /*
        g2d.drawImage(derIma,530, 540, 80, 95, this);
        g2d.drawImage(derIma,460, 590, 80, 95, this);
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
